
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package svgger.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int REPEAT = 14;
  public static final int PROGRAM = 2;
  public static final int OPMUL = 10;
  public static final int LBRA = 4;
  public static final int NUMBER = 15;
  public static final int OPMINUS = 9;
  public static final int LPAR = 6;
  public static final int EOF = 0;
  public static final int RBRA = 5;
  public static final int DOT = 12;
  public static final int COMMA = 13;
  public static final int error = 1;
  public static final int IDENTIFIER = 16;
  public static final int OPPLUS = 8;
  public static final int FUNCTION = 3;
  public static final int RPAR = 7;
  public static final int OPDIV = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "FUNCTION",
  "LBRA",
  "RBRA",
  "LPAR",
  "RPAR",
  "OPPLUS",
  "OPMINUS",
  "OPMUL",
  "OPDIV",
  "DOT",
  "COMMA",
  "REPEAT",
  "NUMBER",
  "IDENTIFIER"
  };
}

